<?php
/**
 * User: Alan Laspina
 * Date: 23/02/2023
 * Time: 10:09 AM
 */

namespace src\Helpers;

class SET
{
    const ESTADO_CONTRIBUYENTE_CANCELADO = 'CANCELADO';

    const ESTADO_CONTRIBUYENTE_CANCELADO_DEFINITIVO = 'CANCELADO DEFINITIVO';

    const ESTADO_CONTRIBUYENTE_BLOQUEADO = 'BLOQUEADO';

    const ESTADO_CONTRIBUYENTE_SUSPENSION_TEMPORAL = 'SUSPENSION TEMPORAL';

    const ESTADO_CONTRIBUYENTE_ACTIVO = 'ACTIVO';
}
